name: publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
          run: |
                docker build . --tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
                docker push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
